Panels:
  - Class: rviz/Displays
    Help Height: 84
    Name: Displays
    Property Tree Widget:
      Expanded:
        - /MotionPlanning1
        - /MotionPlanning1/Scene Geometry1
        - /MotionPlanning1/Scene Robot1
        - /MotionPlanning1/Planning Request1
        - /MotionPlanning1/Planning Metrics1
        - /MotionPlanning1/Planned Path1
      Splitter Ratio: 0.5
    Tree Height: 377
  - Class: rviz/Help
    Name: Help
  - Class: rviz/Views
    Expanded:
      - /Current View1
    Name: Views
    Splitter Ratio: 0.5
Preferences:
  PromptSaveOnExit: true
Toolbars:
  toolButtonStyle: 2
Visualization Manager:
  Class: ""
  Displays:
    - Alpha: 0.5
      Cell Size: 1
      Class: rviz/Grid
      Color: 160; 160; 164
      Enabled: true
      Line Style:
        Line Width: 0.029999999329447746
        Value: Lines
      Name: Grid
      Normal Cell Count: 0
      Offset:
        X: 0
        Y: 0
        Z: 0
      Plane: XY
      Plane Cell Count: 10
      Reference Frame: <Fixed Frame>
      Value: true
    - Acceleration_Scaling_Factor: 0.1
      Class: moveit_rviz_plugin/MotionPlanning
      Enabled: true
      Move Group Namespace: ""
      MoveIt_Allow_Approximate_IK: false
      MoveIt_Allow_External_Program: false
      MoveIt_Allow_Replanning: false
      MoveIt_Allow_Sensor_Positioning: false
      MoveIt_Planning_Attempts: 10
      MoveIt_Planning_Time: 5
      MoveIt_Use_Cartesian_Path: false
      MoveIt_Use_Constraint_Aware_IK: false
      MoveIt_Workspace:
        Center:
          X: 0
          Y: 0
          Z: 0
        Size:
          X: 2
          Y: 2
          Z: 2
      Name: MotionPlanning
      Planned Path:
        Color Enabled: false
        Interrupt Display: false
        Links:
          All Links Enabled: true
          Expand Joint Details: false
          Expand Link Details: false
          Expand Tree: false
          Link Tree Style: Links in Alphabetic Order
          panda_hand:
            Alpha: 1
            Show Axes: false
            Show Trail: false
            Value: true
          panda_hand_sc:
            Alpha: 1
            Show Axes: false
            Show Trail: false
            Value: true
          panda_hand_tcp:
            Alpha: 1
            Show Axes: false
            Show Trail: false
          panda_hand_tcp2:
            Alpha: 1
            Show Axes: false
            Show Trail: false
          panda_leftfinger:
            Alpha: 1
            Show Axes: false
            Show Trail: false
            Value: true
          panda_link0:
            Alpha: 1
            Show Axes: false
            Show Trail: false
            Value: true
          panda_link0_sc:
            Alpha: 1
            Show Axes: false
            Show Trail: false
            Value: true
          panda_link1:
            Alpha: 1
            Show Axes: false
            Show Trail: false
            Value: true
          panda_link1_sc:
            Alpha: 1
            Show Axes: false
            Show Trail: false
            Value: true
          panda_link2:
            Alpha: 1
            Show Axes: false
            Show Trail: false
            Value: true
          panda_link2_sc:
            Alpha: 1
            Show Axes: false
            Show Trail: false
            Value: true
          panda_link3:
            Alpha: 1
            Show Axes: false
            Show Trail: false
            Value: true
          panda_link3_sc:
            Alpha: 1
            Show Axes: false
            Show Trail: false
            Value: true
          panda_link4:
            Alpha: 1
            Show Axes: false
            Show Trail: false
            Value: true
          panda_link4_sc:
            Alpha: 1
            Show Axes: false
            Show Trail: false
            Value: true
          panda_link5:
            Alpha: 1
            Show Axes: false
            Show Trail: false
            Value: true
          panda_link5_sc:
            Alpha: 1
            Show Axes: false
            Show Trail: false
            Value: true
          panda_link6:
            Alpha: 1
            Show Axes: false
            Show Trail: false
            Value: true
          panda_link6_sc:
            Alpha: 1
            Show Axes: false
            Show Trail: false
            Value: true
          panda_link7:
            Alpha: 1
            Show Axes: false
            Show Trail: false
            Value: true
          panda_link7_sc:
            Alpha: 1
            Show Axes: false
            Show Trail: false
            Value: true
          panda_link8:
            Alpha: 1
            Show Axes: false
            Show Trail: false
          panda_rightfinger:
            Alpha: 1
            Show Axes: false
            Show Trail: false
            Value: true
        Loop Animation: false
        Robot Alpha: 0.5
        Robot Color: 150; 50; 150
        Show Robot Collision: false
        Show Robot Visual: true
        Show Trail: false
        State Display Time: 1x
        Trail Step Size: 1
        Trajectory Topic: move_group/display_planned_path
        Use Sim Time: false
      Planning Metrics:
        Payload: 1
        Show Joint Torques: false
        Show Manipulability: false
        Show Manipulability Index: false
        Show Weight Limit: false
        TextHeight: 0.07999999821186066
      Planning Request:
        Colliding Link Color: 255; 0; 0
        Goal State Alpha: 1
        Goal State Color: 250; 128; 0
        Interactive Marker Size: 0
        Joint Violation Color: 255; 0; 255
        Planning Group: panda_manipulator
        Query Goal State: false
        Query Start State: false
        Show Workspace: false
        Start State Alpha: 1
        Start State Color: 0; 255; 0
      Planning Scene Topic: move_group/monitored_planning_scene
      Robot Description: robot_description
      Scene Geometry:
        Scene Alpha: 1
        Scene Color: 50; 230; 50
        Scene Display Time: 0.009999999776482582
        Show Scene Geometry: true
        Voxel Coloring: Z-Axis
        Voxel Rendering: Occupied Voxels
      Scene Robot:
        Attached Body Color: 150; 50; 150
        Links:
          All Links Enabled: true
          Expand Joint Details: false
          Expand Link Details: false
          Expand Tree: false
          Link Tree Style: Links in Alphabetic Order
          panda_hand:
            Alpha: 1
            Show Axes: false
            Show Trail: false
            Value: true
          panda_hand_sc:
            Alpha: 1
            Show Axes: false
            Show Trail: false
            Value: true
          panda_hand_tcp:
            Alpha: 1
            Show Axes: false
            Show Trail: false
          panda_hand_tcp2:
            Alpha: 1
            Show Axes: false
            Show Trail: false
          panda_leftfinger:
            Alpha: 1
            Show Axes: false
            Show Trail: false
            Value: true
          panda_link0:
            Alpha: 1
            Show Axes: false
            Show Trail: false
            Value: true
          panda_link0_sc:
            Alpha: 1
            Show Axes: false
            Show Trail: false
            Value: true
          panda_link1:
            Alpha: 1
            Show Axes: false
            Show Trail: false
            Value: true
          panda_link1_sc:
            Alpha: 1
            Show Axes: false
            Show Trail: false
            Value: true
          panda_link2:
            Alpha: 1
            Show Axes: false
            Show Trail: false
            Value: true
          panda_link2_sc:
            Alpha: 1
            Show Axes: false
            Show Trail: false
            Value: true
          panda_link3:
            Alpha: 1
            Show Axes: false
            Show Trail: false
            Value: true
          panda_link3_sc:
            Alpha: 1
            Show Axes: false
            Show Trail: false
            Value: true
          panda_link4:
            Alpha: 1
            Show Axes: false
            Show Trail: false
            Value: true
          panda_link4_sc:
            Alpha: 1
            Show Axes: false
            Show Trail: false
            Value: true
          panda_link5:
            Alpha: 1
            Show Axes: false
            Show Trail: false
            Value: true
          panda_link5_sc:
            Alpha: 1
            Show Axes: false
            Show Trail: false
            Value: true
          panda_link6:
            Alpha: 1
            Show Axes: false
            Show Trail: false
            Value: true
          panda_link6_sc:
            Alpha: 1
            Show Axes: false
            Show Trail: false
            Value: true
          panda_link7:
            Alpha: 1
            Show Axes: false
            Show Trail: false
            Value: true
          panda_link7_sc:
            Alpha: 1
            Show Axes: false
            Show Trail: false
            Value: true
          panda_link8:
            Alpha: 1
            Show Axes: false
            Show Trail: false
          panda_rightfinger:
            Alpha: 1
            Show Axes: false
            Show Trail: false
            Value: true
        Robot Alpha: 0.5
        Show Robot Collision: false
        Show Robot Visual: true
      Value: true
      Velocity_Scaling_Factor: 0.1
    - Class: rviz/Image
      Enabled: false
      Image Topic: /rgb/image_rect_color
      Max Value: 1
      Median window: 5
      Min Value: 0
      Name: Image
      Normalize Range: true
      Queue Size: 2
      Transport Hint: raw
      Unreliable: false
      Value: false
    - Alpha: 1
      Autocompute Intensity Bounds: true
      Autocompute Value Bounds:
        Max Value: 10
        Min Value: -10
        Value: true
      Axis: Z
      Channel Name: intensity
      Class: rviz/PointCloud2
      Color: 255; 255; 255
      Color Transformer: RGB8
      Decay Time: 0
      Enabled: true
      Invert Rainbow: false
      Max Color: 255; 255; 255
      Min Color: 0; 0; 0
      Name: PointCloud2
      Position Transformer: XYZ
      Queue Size: 10
      Selectable: true
      Size (Pixels): 3
      Size (m): 0.0010000000474974513
      Style: Flat Squares
      Topic: /points2
      Unreliable: false
      Use Fixed Frame: true
      Use rainbow: true
      Value: true
  Enabled: true
  Global Options:
    Background Color: 48; 48; 48
    Default Light: true
    Fixed Frame: panda_base
    Frame Rate: 30
  Name: root
  Tools:
    - Class: rviz/Interact
      Hide Inactive Objects: true
    - Class: rviz/MoveCamera
    - Class: rviz/Select
  Value: true
  Views:
    Current:
      Class: rviz/Orbit
      Distance: 2.2244315147399902
      Enable Stereo Rendering:
        Stereo Eye Separation: 0.05999999865889549
        Stereo Focal Distance: 1
        Swap Stereo Eyes: false
        Value: false
      Field of View: 0.75
      Focal Point:
        X: -0.18561683595180511
        Y: -0.06823498010635376
        Z: 0.08725631237030029
      Focal Shape Fixed Size: true
      Focal Shape Size: 0.05000000074505806
      Invert Z Axis: false
      Name: Current View
      Near Clip Distance: 0.009999999776482582
      Pitch: 0.3950006067752838
      Target Frame: panda_link0
      Yaw: 5.869952201843262
    Saved: ~
Window Geometry:
  Displays:
    collapsed: true
  Height: 1376
  Help:
    collapsed: false
  Hide Left Dock: true
  Hide Right Dock: false
  Image:
    collapsed: false
  MotionPlanning:
    collapsed: true
  MotionPlanning - Trajectory Slider:
    collapsed: false
  QMainWindow State: 000000ff00000000fd0000000200000000000002b700000506fc0200000008fb000000100044006900730070006c006100790073000000003d0000020a000000c900fffffffb0000000800480065006c00700000000342000000bb0000006e00fffffffb0000000a00560069006500770073000000010c000000a4000000a400fffffffb0000000c00430061006d00650072006100000002ff000001610000000000000000fb0000001e004d006f00740069006f006e00200050006c0061006e006e0069006e00670100000374000001890000000000000000fb00000044004d006f00740069006f006e0050006c0061006e006e0069006e00670020002d0020005400720061006a006500630074006f0072007900200053006c00690064006500720000000000ffffffff0000001600000016fb0000001c004d006f00740069006f006e0050006c0061006e006e0069006e0067000000024d000002f60000017d00fffffffb0000002600480061006e0064004500790065002000430061006c006900620072006100740069006f006e0000000362000001e10000000000000000000000010000027e000003b9fc0200000001fb0000000a0049006d006100670065000000003d000003b90000001600ffffff000004640000050600000001000000020000000100000002fc0000000100000002000000010000000a0054006f006f006c00730100000000ffffffff0000000000000000
  Views:
    collapsed: false
  Width: 1124
  X: 72
  Y: 1107
